### ISSUE TITLE
Slight Issue

### ISSUE THREAD

**Issue by KadetKai** [jwktje/langorhythm#2]
<img width="1274" alt="screen shot 2016-02-17 at 10 32 56 pm" src="https://cloud.githubusercontent.com/assets/10346987/13133957/7aef68fe-d5c6-11e5-8bde-0832226aab14.png">
So from what I can interpret from this, as I am fairly new to coding, is that your coding is specifically calling for a file/directory, "Users/jwktje/Development...", that is not present on my computer even after downloading the ZIP and following the steps you also outlined on Youtube. I hope that you see this because I am fascinated by your work and belief in creativity, especially in music, (I also know of your collaborations with Andrew as well as your own channel). Thanks a lot!

**Comment by jwktje** [comment]
Hey man!
Fair point. Didn't account for that. It's an easy fix. 
If you want to fix it quickly for your situation you can just change the file server/server.js. 
Change the 4th line to this:
`Meteor.tempDir = "/Users/GameHead/Downloads/langorhythm-master/.midifiles/";`

I'll fix this in the future, and when I do i'll close this issue

**Comment by KadetKai** [comment]
Okay thanks man!

**Comment by jwktje** [comment]
@therebelrobot submitted a pull request to solve the path issue. It's merged now so the master branch should not produce this error anymore. Long story short, let me know if it works now and I'll close the issue

**Comment by KadetKai** [comment]
Oh yea, I tried it the moment you commented about that and it worked perfectly. Probably should've mentioned it under his issue as well to save you the trouble, but I wasn't sure it was the same thing. Anyways, thanks and yes you can close the issue.
